name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
version: 1.61
authors: [Friwi, bergerkiller, lenis0012, timstans]
metrics: true
load: startup
description: Is used in all of my plugins to re-use common functions
softdepend: [Vault, ProtocolLib, Spout]
dev-url: None
commands:
    commondebug:
        description: Developer debugging commands for changing values
        aliases: [debug]
        usage: /debug [name] [value...]